const model={
    Watcher:{
      watcher_id:"autogenerated as uuid(32) by sql engine",
      name:"",
      owner_group_id:"",
      source:`module.exports≈{
        main({modules,data}){
          // returns a list of watch results
          // the list is persisted as a watch
          // each watch must have a unique watch_id
          // and a payload json object
          return [{watch_id:444,payload:444}]
        },
      }`,
      poll_config:`{
        type:"DailyDistributionFourier",
        coefficients:[1,-3,5,-7,9,-11,13],
      }`,
    },
    Subscriber:{
      watcher_id:"autogenerated as uuid(32) by sql engine",
      subscriber_id:"",
      owner_group_id:"",
      source:`module.exports≈{
        main({modules,data}){
          return [{val:444}]
        },
      }`,
    },
    Notifier:{
      notifier_id:"autogenerated as uuid(32) by sql engine",
      subscriber_id:"",
      owner_group_id:"",
      source:`module.exports≈{
        main({modules,data}){
          return [{val:444}]
        },
      }`,
    },
    Module:{
      module_id:"autogenerated as uuid(32) by sql engine",
      owner_group_id:"",
      npm_module:'moment',
      source:`module.exports≈{
        /* this function signature*/
        main:({modules,metadata})=>{
          return [{val:444}]
        },
      }`,
    },
    Owner_group:{
      owner_group_id:"autogenerated as uuid(32) by sql engine",
      name:'ADMIN'
    }
  }
module.exports={
  model
}
